version: '2'
services:
  sensor:
    container_name: mysensor
    image: rolyatwilson/sensor-client
    ports: 
      - "80:8080"
  controller:
    container_name: mycontroller
    image: rolyatwilson/game-controller
    ports: 
      - "81:8080"
    environment:
      - ADMIN_TOKEN=1234
      - AUTO_READINGS='false'
  gateway:
    container_name: mygateway
    image: rolyatwilson/gateway
    depends_on:
      - sensor
      - controller
    environment:
      - SENSOR_ENDPOINT=107.170.234.44:80
      - GC_ENDPOINT=107.170.234.44:81
  dashboard:
    container_name: dashboard
    image: emccode/mars-challenge-dashboard
    ports: 
      - "82:80"
    depends_on: 
      - controller
    environment:
      - WS_ENDPOINT=107.170.234.44:81/ws
  storage:
    container_name: postgresdb
    image: rolyatwilson/storage
    ports:
      - "5432"
  backup:
    container_name: dbbackups
    image: rolyatwilson/backups
    ports:
      - "22"
